services:
  heroku:
    container_name: heroku-bot
    build: .
    volumes:
      - heroku_data:/data
    restart: unless-stopped
    ports:
      - "${PORT:-8888}:8888"
    environment:
      - DOCKER=true

volumes:
  heroku_data:
